# Generated by Django 4.2.1 on 2024-09-07 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('isActive', models.BooleanField(default=False)),
                ('person_type', models.CharField(blank=True, choices=[('per_person', 'Per Person'), ('total', 'Total')], max_length=20, null=True)),
                ('category', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='products', to='pages.category')),
            ],
        ),
    ]
