# Generated by Django 4.2.1 on 2024-09-11 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pages', '0003_product_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='imageUrl',
        ),
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='', upload_to='images'),
        ),
    ]
